name: Refill TV

on:
  schedule:
    - cron:  '0 0 */3 * *' 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  refill: 
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Execute script
        run: python ./scripts/refill_tv.py

      - name: Commit changes (if any)
        run: |
          git config --global user.name 'Reijaff'
          git config --global user.email 'interlord406@gmail.com'
          git add .
          git commit -m "Automated update from refill_tv.py $(date)"

      - name: Push changes (if any)
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'schedule' || steps.commit-changes.outcome == 'success' }}

      - name: Get commit hash (if pushed)
        id: get-commit-hash
        if: ${{ steps.push-changes.outcome == 'success' }} 
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT