name: Refill TV

on:
  schedule:
    - cron:  '0 0 */3 * *' 
  workflow_dispatch: 

permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  refill: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Execute script
        run: python ./scripts/refill_tv.py

      - name: Commit & Push changes (if any)
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Reijaff
          author_email: interlord406@gmail.com
          message: "Automated update from refill_tv.py"
          add: '.'
          push: true
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
