name: Refill TV and Deploy to GitHub Pages

on:
  schedule:
    - cron:  '0 0 */3 * *' 
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true 

jobs:
  refill: 
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }} # Expose the commit hash as an output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Execute script
        run: python ./scripts/refill_tv.py

      - name: Commit changes (if any)
        run: |
          git config --global user.name 'Reijaff'
          git config --global user.email 'interlord406@gmail.com'
          git add .
          git commit -m "Automated update from refill_tv.py $(date)"


      - name: Push changes (if any)
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'schedule' || steps.commit-changes.outcome == 'success' }}

      - name: Get commit hash (if pushed)
        id: get-commit-hash
        if: ${{ steps.push-changes.outcome == 'success' }} 
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  deploy: 
    needs: refill 
    if: ${{ needs.refill.outputs.commit_hash != '' || github.event_name == 'workflow_dispatch' }} # Deploy if there's a new commit hash or it's manual
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.refill.outputs.commit_hash }}  # Use the commit hash from refill

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4