name: Refill TV and deploy to Github Pages

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch: 

permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # More specific concurrency control
  cancel-in-progress: true

jobs:
  refill: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' 
          cache-dependency-path: 'requirements.txt' # Cache based on dependencies

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Execute script
        run: python ./scripts/refill_tv.py

      - name: Get commit hash (if changes were made)
        id: get-commit-hash
        if: steps.add-and-commit.outputs.committed == 'true'
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Commit & Push changes (if any)
        id: add-and-commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Reijaff
          author_email: interlord406@gmail.com
          message: "Automated update from refill_tv.py"
          add: '.'
          push: true
      
      - name: Setup Pages
        if: steps.add-and-commit.outputs.committed == 'true' # Only if changes were committed
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: steps.add-and-commit.outputs.committed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        if: steps.add-and-commit.outputs.committed == 'true'
        id: deployment
        uses: actions/deploy-pages@v4