name: Refill TV

on:
  schedule:
    - cron:  '0 0 */3 * *' 
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  refill: 
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }} 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          cache: 'pip' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Execute script
        run: python ./scripts/refill_tv.py

      - name: Commit & Push changes (if any)
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Reijaff
          author_email: interlord406@gmail.com
          message: "Automated update from refill_tv.py $(date)"
          add: '.'
          push: true
      
      - name: Dispatch deploy workflow
        if: steps.add-and-commit.outputs.committed == 'true' # Only trigger if commit was successful
        uses: benc-uk/workflow-dispatch@v2
        with:
          workflow: Deploy to GitHub Pages # Name of your deploy.yml workflow
          token: ${{ secrets.GITHUB_TOKEN }} 